### ISSUE TITLE
Not working with Vue 3

### ISSUE THREAD

**Issue by aaqibqadeer** [Saeris/vue-spinners#82]
The Package is working with Vue 3. It is showing the following error.
![image](https://user-images.githubusercontent.com/37020354/109432258-2f8f4400-7a2c-11eb-9086-3299ad99ac6c.png)

Is this package support Vue 3 or not? because the readme file does not mention the supported version.

Thank you,

**Comment by Saeris** [comment]
This package only supports Vue 2 and I don't have any plans at this time to update it. You're welcome to create your own fork or I would suggest using the source code here as a reference for implementing whichever of the components you are interested in your project.
